# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4992bdbd0b5dd8d3664c21150cf19be0d48107b8fb9027d21095db492a0fd57b9357f9efc90eda32521bcba1ebc7b90d51eba93040b6d0908aed3cb5cf816f08

test:
  secret_key_base: 075c9e76c05435b2d7c1128e4a9b8b8435cdd84909a3b125c3b76cf940815422d5e1356f33e3a5e45d97c11b577c2ae25699a7f52e6e8c35f7fcd65fe2bf15c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
